### ISSUE TITLE
M1 Mac support

### ISSUE THREAD

**Issue by kyranb** [FairwindsOps/homebrew-tap#4]
Is there currently any plans to release an M1 build?

https://github.com/FairwindsOps/homebrew-tap/blob/master/Formula/nova.rb

**Comment by lucasreed** [comment]
Yes! Sorry for the delay responding here. I'm working on a release for nova now.

**Comment by lucasreed** [comment]
This should be fixed with https://github.com/FairwindsOps/nova/pull/59
